# Generated by Django 6.0.5 on 2026-06-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('select', 'Dropdown Select'), ('multiselect', 'Multi-Select Checkboxes'), ('boolean', 'Yes / No Toggle'), ('color', 'Color Swatch')], default='text', max_length=50),
        ),
    ]
