# Generated by Django 6.0.5 on 2026-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuschange',
            name='new_status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled')], default=1),
        ),
    ]
