# Generated by Django 6.0.5 on 2026-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_change', '0002_alter_orderstatuschange_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuschange',
            name='new_status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Payment Confirmed'), (3, 'Confirmed'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Payment Confirmed'), (3, 'Confirmed'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Canceled')], default=1),
        ),
    ]
