# Generated by Django 6.0.5 on 2026-07-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_change', '0003_alter_orderstatuschange_new_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatuschange',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='orderstatuschange',
            name='tracking_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderstatuschange',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
