# Generated by Django 6.0.5 on 2026-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
