# Generated by Django 6.0.5 on 2026-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
