# Generated by Django 6.0.5 on 2026-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sku',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
