# Generated by Django 6.0.5 on 2026-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='sku',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
