# Generated by Django 6.0.5 on 2026-07-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_customers', '0001_initial'),
        ('product_variants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomers',
            name='variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_variants.productvariant'),
        ),
    ]
