# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_customers', '0002_alter_notifycustomers_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomers',
            name='is_notified',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
