# Generated by Django 6.0.5 on 2026-07-02 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', max_length=15)),
                ('discount_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
