# Generated by Django 6.0.5 on 2026-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_code_coupon_coupon_code_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
