# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=15),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1),
        ),
    ]
