# Generated by Django 6.0.5 on 2026-07-09 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=15),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_total',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
