# Generated by Django 6.0.5 on 2026-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0002_orderpayment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
