# Generated by Django 6.0.5 on 2026-07-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0003_alter_orderpayment_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='refund_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
