# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0004_remove_orderpayment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Success', 'Success'), ('Failed', 'Failed')], default='Created', max_length=50),
        ),
    ]
