# Generated by Django 6.0.5 on 2026-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaddress',
            name='address_type',
            field=models.CharField(choices=[('SHIPPING', 'Shipping Address'), ('BILLING', 'Billing Address')], default='BILLING', max_length=10),
        ),
    ]
