# Generated by Django 6.0.5 on 2026-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0003_alter_productimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_base',
            field=models.BooleanField(default=0),
        ),
    ]
