# Generated by Django 6.0.5 on 2026-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
