# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1),
        ),
    ]
