# Generated by Django 6.0.5 on 2026-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_options_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sku',
            field=models.CharField(max_length=200),
        ),
    ]
