# Generated by Django 6.0.5 on 2026-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
