# Generated by Django 6.0.5 on 2026-06-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_customer_email_cart_customer_mo_no'),
        ('cart_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPayment',
            new_name='CartPayment',
        ),
    ]
