# Generated by Django 6.0.5 on 2026-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_payment', '0002_rename_orderpayment_cartpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='payment_method',
            field=models.CharField(default='online', max_length=50),
        ),
    ]
