# Generated by Django 6.0.5 on 2026-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_payment', '0016_alter_cartpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Cod', 'Cod')], default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Success', 'Success'), ('Failed', 'Failed')], default='Created', max_length=50),
        ),
    ]
