# Generated by Django 6.0.5 on 2026-07-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
        ('product_variants', '0002_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_variants.productvariant'),
        ),
    ]
