# Generated by Django 6.0.5 on 2026-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_cart_total_alter_cart_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_amount',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.CharField(blank=True, default='Flate Rate', max_length=200, null=True),
        ),
    ]
