# Generated by Django 6.0.5 on 2026-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_customer_email_cart_customer_mo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
