# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_coupon_cart_coupon_code_cart_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.BooleanField(choices=[(0, 'Deactive'), (1, 'Active')], default=1),
        ),
    ]
