# Generated by Django 6.0.5 on 2026-06-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('row_total', models.FloatField(blank=True, default=None, null=True)),
                ('order_total', models.FloatField(blank=True, default=None, null=True)),
                ('discount_rate', models.FloatField(blank=True, default=None, null=True)),
                ('discount_amount', models.FloatField(blank=True, default=None, null=True)),
                ('shipping_amount', models.FloatField(blank=True, default=100, null=True)),
                ('shipping_method', models.CharField(blank=True, default='Flate Rate', max_length=200, null=True)),
                ('order_id', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=1)),
                ('coupon', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
