# Generated by Django 6.0.5 on 2026-06-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_number',
        ),
    ]
