# Generated by Django 6.0.5 on 2026-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_id_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_mo_no',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
