# Generated by Django 6.0.5 on 2026-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled')], default=1),
        ),
    ]
