# Generated by Django 6.0.5 on 2026-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_tracking_link_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Payment Confirmed'), (3, 'Confirmed'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Canceled')], default=1),
        ),
    ]
