# Generated by Django 6.0.5 on 2026-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_cancellation_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
