# Generated by Django 6.0.5 on 2026-07-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_refund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_id',
        ),
    ]
