# Generated by Django 6.0.5 on 2026-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
