# Generated by Django 6.0.5 on 2026-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_coupon_order_coupon_code_order_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cod'), (1, 'Online')], default=0),
        ),
    ]
