# Generated by Django 6.0.5 on 2026-06-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_items', '0001_initial'),
        ('categories', '0003_alter_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
