# Generated by Django 6.0.5 on 2026-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_reseller_price_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
