# Generated by Django 6.0.5 on 2026-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_brand_id_remove_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1),
        ),
    ]
