# Generated by Django 6.0.5 on 2026-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
