# Generated by Django 6.0.5 on 2026-07-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_image_url'),
        ('products', '0007_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
    ]
